(in-package :aoc-2021)

(defun parse-file ()
  (parse-lines (parse-list (parse-digit) "")))

(defun most-common (numbers)
  (let* ((half-length (/ (length numbers) 2))
         (one-counts (reduce (lambda (a b) (map 'list #'+ a b)) numbers))
         (most-common (mapcar (lambda (c) (cond
                                            ((= c half-length) :eq)
                                            ((> c half-length) 1)
                                            (t 0)))
                              one-counts)))
    most-common))

(defun get-oxygen-rating (position numbers)
  (if (= 1 (length numbers))
      (car numbers)
      (let ((most-common (most-common numbers)))
        (case (elt most-common position)
          (:eq (get-oxygen-rating (1+ position)
                                  (remove-if (lambda (word)
                                               (= (elt word position) 0))
                                             numbers)))
          (t (get-oxygen-rating (1+ position)
                                (remove-if (lambda (word)
                                             (= (elt word position)
                                                (- 1 (elt most-common position))))
                                           numbers)))))))

(defun get-co2-rating (position numbers)
  (if (= 1 (length numbers))
      (car numbers)
      (let ((most-common (most-common numbers)))
        (case (elt most-common position)
          (:eq (get-co2-rating (1+ position)
                                  (remove-if (lambda (word)
                                               (= (elt word position) 1))
                                             numbers)))
          (t (get-co2-rating (1+ position)
                                (remove-if (lambda (word)
                                             (= (elt word position)
                                                (elt most-common position)))
                                             numbers)))))))

(defun day3 (input)
  (let* ((parsed (run-parser (parse-file) input)))
    (* (digits-to-int (get-oxygen-rating 0 parsed))
       (digits-to-int (get-co2-rating 0 parsed)))))
